name: nightly cron

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"

      - name: run
        run: go run .
        env:
          RH_CLIENT_ID: ${{ secrets.RH_CLIENT_ID }}
          RH_USERNAME: ${{ secrets.RH_USERNAME }}
          RH_PASSWORD: ${{ secrets.RH_PASSWORD }}
          RH_DEVICE_TOKEN: ${{ secrets.RH_DEVICE_TOKEN }}
          ZERODHA_USER_ID: ${{ secrets.ZERODHA_USER_ID }}
          ZERODHA_PASSWORD: ${{ secrets.ZERODHA_PASSWORD }}
          ZERODHA_TOTP_SECRET: ${{ secrets.ZERODHA_TOTP_SECRET }}
          FIREFLY_TOKEN: ${{ secrets.FIREFLY_TOKEN }}
          FIREFLY_HOST: ${{ vars.FIREFLY_HOST }}
          ROBINHOOD_FIREFLY_ID: ${{ vars.ROBINHOOD_FIREFLY_ID }}
          ZERODHA_FIREFLY_ID: ${{ vars.ZERODHA_FIREFLY_ID }}
          FIDELITY_FIREFLY_ID: ${{ vars.FIDELITY_FIREFLY_ID }}
          FIDELITY_BALANCE: ${{ secrets.FIDELITY_BALANCE }}
